a2lix_translation_form:
    locale_provider: default       # [1]
    locales: [es, en]      # [1-a]
    default_locale: es             # [1-b]
    required_locales: [es]         # [1-c]
    # templating: "@A2lixTranslationForm/bootstrap_3_layout.html.twig"
    templating: "admin/a2lix_tabs.html.twig"
