twig:
    default_path: '%kernel.project_dir%/templates'

    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
        - admin/slug.html.twig
        - admin/a2lix_tabs.html.twig
        - admin/image-preview.html.twig
        - bootstrap_5_layout.html.twig

when@test:
    twig:
        strict_variables: true
