# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Components\Form\Type\ImagePreviewType:
        arguments:
            $mediaManager: "@sonata.media.manager.media"

    App\Components\Form\Type\FilePreviewType :
        arguments:
            $mediaManager: "@sonata.media.manager.media"

    App\Controller\ApiController:
        arguments:
            $mediaProvider: '@sonata.media.provider.image'


    admin.champion:
        class: App\Admin\ChampionAdmin
        tags:
            - name: sonata.admin
              model_class: App\Entity\Champion
              manager_type: orm
              group: "Champions"
              label: "Champions"
              icon: '<i class="fa fa-users"></i>'

    admin.hability:
        class: App\Admin\HabilityAdmin
        tags:
            - name: sonata.admin
              model_class: App\Entity\Hability
              manager_type: orm
              group: "Champions"
              label: "Hability"
              icon: '<i class="fa fa-users"></i>'
              show_in_dashboard: false
            #   controller: App\Controller\Admin\VideoController
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
